export const GET_BLOG_CONTENT = 'GET_BLOG_CONTENT';
export const SET_BLOG_DETAIL = 'SET_BLOG_DETAIL';
export const GET_WORKS_CONTENT = 'GET_WORKS_CONTENT';
export const SET_WORKS_DETAIL = 'SET_WORKS_DETAIL';
export const GET_WORKS_GALLERY = 'GET_WORKS_GALLERY';
export const SET_GALLERY_DETAIL = 'SET_GALLERY_DETAIL';